import { NextResponse } from "next/server";
import { supabase } from "@utils";

/*
  @params: 
    messageID: A UUID for message as ID
    question: The user query
    answer: The LLM's answer
    sections: The sections generated by the cosine similarity
    similarity: The array of cosine similarities
    model: The model that is being used currently
*/
export async function POST(req) {

  try {

    const body = await req.json();
    console.log("Body is: ",body);
    
    const { data, error } = await supabase
      .from("testing")
      .insert([
        {
          message_id: body.messageID,
          question: body.question,
          answer: body.answer,
          sections: body.sections,
          similarity: body.similarity,
          model: body.model,
        },
      ])
      .select();
        
    
    console.log("Data: ",data);
    console.log("Details: ",error.details);
    console.log("Hint: ",error.hint);
    console.log("Code: ",error.code);
    console.log("Message: ", error.message)
    if(error) {
      console.error(error);
      return NextResponse.json({ message: error.message }, { status: error.code });
    }

    return NextResponse.json({ message: data }, { status: 200 });
  } catch (error) {
    return NextResponse.json({ message: error }, { status: 400 });
  }
}